src/Web/Company.Crm.Web.Mvc/Controllers/AuthController.cs
using Company.Crm.Application.Dtos;
using Company.Crm.Application.Services.Abstracts;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Company.Crm.Web.Mvc.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto model, string? returnUrl)
        {
            // Login işlemi

            // Claim - Ad
            // Identity - Kimlik, Ehliyet, KurumKarti, YemekKarti
            // Principle - Cuzdan (Kimlik, Ehliyet)

            if (ModelState.IsValid)
            {
                var user = _userService.Login(model);

                if (user != null)
                {
                    #region Claim, Identity, Principle

                    // ClaimsIdentity içerisindeki bilgiler (Kimlik'te yazan bilgiler)
                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.Name, user.Name + " " + user.Surname),
                        new Claim(ClaimTypes.GivenName, user.Name),
                        new Claim(ClaimTypes.Surname, user.Surname),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.StreetAddress, ""),
                        new Claim("OzelKey", "OzelValue")
                    };

                    if (user.Roles.Any())
                    {
                        foreach (var role in user.Roles)
                        {
                            claims.Add(new Claim(ClaimTypes.Role, role.Name));
                        }
                    }

                    // ClaimsIdentity (Kimlik)
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    // Principle (Cüzdan)
                    var claimsPrinciple = new ClaimsPrincipal(claimsIdentity);

                    #endregion

                    var authProperties = new AuthenticationProperties()
                    {
                        IsPersistent = model.RememberMe,
                        ExpiresUtc = DateTime.Now.AddDays(30)
                    };

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        claimsPrinciple,
                        authProperties
                    );

                    return Redirect(returnUrl == null ? "/" : returnUrl);
                }
            }

            ModelState.AddModelError(string.Empty, "Kullanıcı adı veya şifre yanlış");

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return Redirect("/");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterDto model)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.Register(model);
                if (user != null)
                {
                    return RedirectToAction("RegisterSuccess");
                }
            }

            ModelState.AddModelError(string.Empty, "Kayıt sırasında bir hata oluştu");

            return View();
        }

        public IActionResult RegisterSuccess()
        {
            return View();
        }

        public IActionResult EmailActivation(string email, string activationKey)
        {
            var isSuccess = _userService.ActivateUserByEmail(email, activationKey);
            if (isSuccess)
            {
                return RedirectToAction("EmailActivationSuccess");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public IActionResult EmailActivationSuccess()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public IActionResult RemindPassword()
        {
            // RemindPassword view içerisinde bir email alanı içeren bir form oluştur.

            // Formdan gelen email adresine UserService->RemindPassword metodu üzerinden şifre sıfırlama maili gönder

            // RemindPasswordSuccess View'ine yönlendir. Burada da şifre sıfırlama maili gönderilmiştir.

            // Email den gelen bağlantıya tıkladığımızda Auth/ResetPassword metodunda şifre sıfırlama formunu göstereceğiz. Form içerisinde Yeni Şifre ve Yeni Şifre tekrarı alanları olacak.

            // ResetPassword formundan gelen şifreye göre şifre sıfırlama işlemi yapılacak. Şifre sıfırlama işlemini UserService->ResetPassword metodunda yapalım ve Şifre sıfırlama

            // ResetPasswordSuccess View'ine yönlendir. Burada da Şifreniz başarıyla değiştirilmiştir.

            return View();
        }

        [HttpPost]
        public IActionResult RemindPassword(RemindPasswordDto dto)
        {
            _userService.RemindPassword(dto);

            return RedirectToAction("RemindPasswordSuccess");
        }

        public IActionResult RemindPasswordSuccess()
        {
            return View();
        }

        public IActionResult ResetPassword(string email, string resetKey)
        {
            var dto = new ResetPasswordDto() { EmailAddress = email };

            return View(dto);
        }

        [HttpPost]
        public IActionResult ResetPassword(ResetPasswordDto dto)
        {
            _userService.ResetPassword(dto);

            return RedirectToAction("ResetPasswordSuccess");
        }

        public IActionResult ResetPasswordSuccess()
        {
            return View();
        }

        public async Task GoogleLogin(string? returnUrl)
        {
            string redirectUri = Url.Action("GoogleResponse", new { ReturnUrl = returnUrl });

            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new AuthenticationProperties()
            {
                RedirectUri = redirectUri
            });
        }

        public async Task<IActionResult> GoogleResponse(string returnUrl = "/")
        {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            if (result.Succeeded)
            {
                var principal = result.Principal;
                var claims = principal.Identities.FirstOrDefault()?.Claims.ToList();

                var photoUrl = principal.FindFirst("urn:google:picture")?.Value;
                var emailAddress = principal.FindFirst(ClaimTypes.Email)?.Value;

                var isUserExist = _userService.GetAll().Any(e => e.Email == emailAddress);
                if (!isUserExist)
                {
                    var userDto = new RegisterDto
                    {
                        EmailAddress = emailAddress,
                        Name = principal.FindFirst(ClaimTypes.GivenName)?.Value,
                        Surname = principal.FindFirst(ClaimTypes.Surname)?.Value,
                        Password = Guid.NewGuid().ToString(),
                    };

                    var registeredUser = _userService.Register(userDto);

                    if (registeredUser != null)
                    {
                        await LoginWithClaims(emailAddress, claims);

                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    await LoginWithClaims(emailAddress, claims);
                }

                return Redirect(returnUrl);
            }

            return RedirectToAction("Login");
        }

        private async Task LoginWithClaims(string? emailAddress, List<Claim>? claims)
        {
            var activeUser = _userService.GetByEmail(emailAddress);
            if (activeUser != null)
            {
                if (activeUser.Roles.Any())
                {
                    foreach (var role in activeUser.Roles)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, role.Name));
                    }

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var claimsPrinciple = new ClaimsPrincipal(claimsIdentity);

                    var authProperties = new AuthenticationProperties()
                    {
                        IsPersistent = true,
                        ExpiresUtc = DateTime.Now.AddDays(30)
                    };

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        claimsPrinciple,
                        authProperties
                    );
                }
            }
        }
    }
}

src/Web/Company.Crm.Web.Mvc/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Company.Crm.Web.Mvc.Controllers;

public class UserController : Controller
{
    private readonly ILogger<UserController> _logger;

    public UserController(ILogger<UserController> logger)
    {
        _logger = logger;
    }

    public IActionResult Profile()
    {
        return View();
    }

    public IActionResult Settings()
    {
        return View();
    }
}

src/Web/Company.Crm.Web.Mvc/Views/Shared/_BasicLayout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.Crm.Web.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.Crm.Web.Mvc.styles.css" asp-append-version="true" />
</head>
<body>

    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Web/Company.Crm.Web.Mvc/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using Company.Crm.Application.Constants;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.Crm.Web.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.Crm.Web.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.Crm.Web.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    @if (User.IsInRole(RoleNameConsts.Administrator))
                                    {
                                        <li><a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home">Admin Panel</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                    }
                                    <li><a class="dropdown-item text-dark" asp-controller="User" asp-action="Profile">Profile</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="User" asp-action="Settings">Settings</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Company.Crm.Web.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>